### PR TITLE
[CNI] Add cni support to the image

### PR DESCRIPTION
**Pull request by oleksiimoisieiev**
Signed-off-by: Oleksii Moisieiev <oleksii_moisieiev@epam.com>

### CODE REVIEW

**Comment by andr2000** [comment]
What is CNI? Is it worth describing in the commit message?

**Comment by oleksiimoisieiev** [comment]
> What is CNI? Is it worth describing in the commit message?

Updated commit message with additional information.

**Review by al1img — COMMENTED** [review]
This should be added to meta-aos as aos_servicemanager dependency

**Comment by varder** [comment]
The change are now in https://github.com/xen-troops/meta-aos-minimal/pull/14
This pull request can be closed

**Comment by al1img** [comment]
Added in meta-aos

**Pull request closed without merging**
